import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import {Nunito_Sans} from 'next/font/google'
import "./globals.css";
import NavBar from "./navbar/page";

// const inter = Inter({ subsets: ["latin"] });

const nunito_Sans = Nunito_Sans({
  subsets: ['latin'],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900", "1000"]
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito_Sans.className}>
        <NavBar />
        {children}
        </body>
    </html>
  );
}
